### ISSUE TITLE
如下报错Could not start http server java.io.IOException: Failed to bind to 【IP】:【端口】

### ISSUE THREAD

**Issue by zoe-may** [yuxuanchiadm/SkyCraftUpdater#15]
根据教程做的，换了很多端口都提示这个。已经尝试过将ip改成0.0.0.0了，可以正常启动，但是一旦将ip改回服务器地址就无法启动了
端口应该是没有被占用的（毕竟换了好多个都是一样）

严重: Could not start http server
java.io.IOException: Failed to bind to 【IP】:【端口】
        at org.skycraft.updater.shades.org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349)
        at org.skycraft.updater.shades.org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310)
        at org.skycraft.updater.shades.org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.skycraft.updater.shades.org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234)
        at org.skycraft.updater.shades.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.skycraft.updater.shades.org.eclipse.jetty.server.Server.doStart(Server.java:401)
        at org.skycraft.updater.shades.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.skycraft.updater.core.Provider.startServer(Provider.java:254)
        at org.skycraft.updater.core.Provider.run(Provider.java:61)
        at org.skycraft.updater.core.Provider.main(Provider.java:315)
Caused by: java.net.BindException: Cannot assign requested address: bind
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:552)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:336)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:88)
        at org.skycraft.updater.shades.org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344)
        ... 9 more

**Comment by zoe-may** [comment]
我不确定是不是服务商的问题，但是服务器都可以正常使用端口，所以就来问问啦

**Comment by zoe-may** [comment]
我知道原因了，启动失败是因为绑定的是域名，服务商的域名是动态的ip，请问有什么解决办法吗？

**Comment by jki135542** [comment]
请问有什么解决办法吗，同样的问题

**Comment by zoe-may** [comment]
> 请问有什么解决办法吗，同样的问题

叫服务商把udp端口打开就行
