### ISSUE TITLE
1.12.2配置独立更新服务器 错误

### ISSUE THREAD

**Issue by XiaoShuaiOwO** [yuxuanchiadm/SkyCraftUpdater#19]
确认已正确填写 Start.bat 文件内容
java -cp Updater-1.12.2-3.0.0.jar org.skycraft.updater.core.Provider client client_manifest.json 0.0.0.0 15555
pause

但是启动后显示
9月 29, 2022 12:31:26 上午 org.skycraft.updater.core.Provider run
信息: Starting updater provider...
9月 29, 2022 12:31:26 上午 org.skycraft.updater.core.Provider precacheManifest
信息: Precaching provider manifest
9月 29, 2022 12:31:26 上午 org.skycraft.updater.core.Provider precacheManifest
严重: Could not load provider manifest
org.skycraft.updater.shades.com.google.gson.stream.MalformedJsonException: Expected name at line 8 column 6 path $[0].ignore-client
	at org.skycraft.updater.shades.com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562)
	at org.skycraft.updater.shades.com.google.gson.stream.JsonReader.doPeek(JsonReader.java:504)
	at org.skycraft.updater.shades.com.google.gson.stream.JsonReader.hasNext(JsonReader.java:413)
	at org.skycraft.updater.core.protocol.v1.ProtocolHandlerV1.precacheManifest(ProtocolHandlerV1.java:56)
	at org.skycraft.updater.core.Provider.precacheManifest(Provider.java:82)
	at org.skycraft.updater.core.Provider.run(Provider.java:57)
	at org.skycraft.updater.core.Provider.main(Provider.java:206)
	Suppressed: java.io.IOException: Incomplete document
		at org.skycraft.updater.shades.com.google.gson.stream.JsonWriter.close(JsonWriter.java:558)
		at org.skycraft.updater.core.protocol.v1.ProtocolHandlerV1.precacheManifest(ProtocolHandlerV1.java:102)
		... 3 more

**Comment by yuxuanchiadm** [comment]
client_manifest.json配置错误导致，建议检查其格式是否正确
