### ISSUE TITLE
Could not start http server

### ISSUE THREAD

**Issue by YifanHere** [yuxuanchiadm/SkyCraftUpdater#2]
我严格的按照配置独立更新服务器的教程进行的，加载完mod后报错。
```
严重: Could not start http server
java.io.IOException: Failed to bind to /1.116.76.104:25566
        at org.skycraft.updater.shades.org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349)
        at org.skycraft.updater.shades.org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310)
        at org.skycraft.updater.shades.org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.skycraft.updater.shades.org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234)
        at org.skycraft.updater.shades.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.skycraft.updater.shades.org.eclipse.jetty.server.Server.doStart(Server.java:401)
        at org.skycraft.updater.shades.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.skycraft.updater.core.Provider.startServer(Provider.java:254)
        at org.skycraft.updater.core.Provider.run(Provider.java:61)
        at org.skycraft.updater.core.Provider.main(Provider.java:315)
Caused by: java.net.BindException: 无法指定被请求的地址
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:461)
        at sun.nio.ch.Net.bind(Net.java:453)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:222)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:85)
        at org.skycraft.updater.shades.org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344)
        ... 9 more`
```

**Comment by yuxuanchiadm** [comment]
服务端绑定ip试试改成0.0.0.0，然后看看端口是否有冲突
